services:
  pweb-dev:
    image: "ghcr.io/myselfakashagarwal/pweb:env"
    container_name: "pweb-dev"
    working_dir: "/app"
    ports:
      - "1111:8080"
    volumes:
      - "$PWD:/app"
    entrypoint: "npm run dev"
    profiles:
      - "development"
      - "pweb"
    restart: "always"

  pweb-build:
    image: "ghcr.io/myselfakashagarwal/pweb:build"
    container_name: "pweb-build"
    user: "root"
    ports:
      - "2222:8080"
    volumes:
      - "$PWD:/app"
      - "$PWD/jobs/pweb_push/:/var/jenkins_home/jobs/pweb_push"
      - "$PWD/jobs/pweb_build/:/var/jenkins_home/jobs/pweb_build"
      - "/var/run/docker.sock:/var/run/docker.sock"
    profiles:
      - "build"
      - "pweb"
    tty: "true"
    restart: "always"

  pweb-deploy:
    image: "ghcr.io/myselfakashagarwal/pweb:latest"
    container_name: "pweb-deploy"
    ports:
      - "80:8082"
    profiles:
      - "pweb"
      - "deploy"
    restart: "always"

  pweb-update:
    image: "containrrr/watchtower"
    container_name: "pweb-update"
    profiles:
      - "pweb"
      - "deploy"
      - "update"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "--interval 10 pweb-deploy"
    restart: "always"

